In [14]:
import pandas as pd

df = pd.read_csv('CombinedFinalDublin2.csv')
df= df.drop('Unnamed: 0', 1)
df.head(32)

,Garda Station,Theft,Assault & Kidnapping,Fraud & Drugs & Weapons,Environment & Public Order,PopulationTotalMale,PopulationTotalFemale,PopulationTotal,PrincipalStatusAtWork,PrincipalStatusLookingForFirstJob,...,GeneralHealthFair,GeneralHealthBad,GeneralHealthVeryBad,GeneralHealthNotStated,Total_Under18Male,Total_Under18Female,Total_Under18,Green,Area,PopulationDensity
0,Balbriggan,193,168,179,470,11746,12296,24042,9191,267,...,1638,281,66,513,4134,3892,8026,9,60.000023,400.699846
1,Ballyfermot,272,173,349,820,13247,14332,27579,9627,339,...,3122,546,133,567,3426,3286,6712,4,8.568579,3218.620030
2,Ballymun,189,217,260,752,10408,11267,21675,6870,269,...,2150,426,75,749,2993,2893,5886,4,7.025158,3085.339783
3,BlackrockCoDublin,243,106,156,354,15003,16975,31978,13827,145,...,1883,284,65,511,3563,3469,7032,3,8.965902,3566.624005
4,Blanchardstown,790,543,579,2084,48192,49886,98078,42376,1007,...,5398,904,195,2698,15255,14502,29757,15,45.287530,2165.673399
5,BridewellDublin,279,174,299,4611,11883,11111,22994,10800,340,...,2209,438,91,862,1636,1546,3182,0,3.005021,7651.860597
6,Cabinteely,230,83,74,310,15800,16954,32754,13227,153,...,2025,303,74,685,4157,3983,8140,35,18.411407,1779.005778
7,Cabra,172,130,157,598,10342,11509,21851,9363,184,...,1916,371,70,775,2366,2331,4697,3,11.359962,1923.509972
8,Clontarf,415,99,113,469,17749,19494,37243,16745,244,...,2903,419,84,725,3949,3698,7647,21,18.083254,2059.529726
9,Coolock,403,279,608,951,25244,26969,52213,20131,418,...,4671,795,169,1343,6946,6642,13588,2,17.676889,2953.743672
10,Donnybrook,299,102,77,457,13507,15191,28698,13484,129,...,1853,342,123,1278,2286,2157,4443,5,8.219549,3491.432368
11,Airport,0,20,82,82,260,147,407,263,2,...,15,4,1,66,19,22,41,0,6.237030,65.255415
12,Dun Laoghaire,378,170,200,1215,17676,19938,37614,15146,176,...,2938,502,124,828,4006,3976,7982,22,11.239514,3346.585953
13,Finglas,389,334,494,1109,19732,21313,41045,15742,394,...,4011,711,155,1294,5563,5160,10723,10,38.189892,1074.760818
14,Fitzgibbon Street,387,201,169,789,9828,9500,19328,8250,430,...,1830,398,97,1381,1511,1573,3084,1,1.874715,10309.834669
15,Garristown,17,10,10,23,1893,1793,3686,1440,20,...,232,32,9,107,604,532,1136,0,83.207734,44.298767
16,Howth,143,69,88,250,10045,10889,20934,8503,97,...,1501,235,40,332,2349,2271,4620,5,14.487512,1444.968583
17,Irishtown,246,68,81,386,11222,12447,23669,13231,114,...,1440,214,50,728,1802,1796,3598,13,13.370166,1770.284709
18,Kevin Street,401,259,272,1186,14740,14332,29072,13293,410,...,2548,476,116,1361,2077,2072,4149,1,2.774478,10478.366461
19,Kilmainham,344,299,217,1039,11724,12183,23907,11192,228,...,2357,524,171,1098,2085,1996,4081,3,4.865736,4913.336912
20,Lucan,224,153,159,463,16999,17770,34769,15299,228,...,1720,287,57,772,5569,5409,10978,4,27.031565,1286.237047
21,Lusk,81,81,47,168,8969,9311,18280,7739,132,...,1126,196,48,338,2819,2878,5697,5,54.564212,335.018127
22,Malahide,199,99,106,373,15674,16218,31892,14378,171,...,1593,223,40,645,4190,3849,8039,4,22.252301,1433.200106
23,Mountjoy,404,233,246,808,11890,11029,22919,9887,257,...,2041,362,81,1622,1828,1608,3436,4,4.049969,5659.055363
24,Pearse Street,744,643,565,3575,9682,9222,18904,10079,200,...,1077,179,50,2233,994,973,1967,3,3.182021,5940.879322
25,Raheny,140,78,157,380,11890,13097,24987,9641,147,...,2386,438,105,389,2856,2826,5682,4,13.654908,1829.891495
26,Santry,343,233,156,659,16713,18973,35686,14141,237,...,3447,668,151,932,3558,3420,6978,22,15.133922,2358.014011
27,Shankill,173,100,161,421,10929,11765,22694,9171,174,...,1618,256,57,462,3218,2969,6187,10,20.719053,1095.320316
28,Skerries,48,51,30,133,5567,5844,11411,4358,74,...,764,108,24,155,1734,1649,3383,7,30.605302,372.843897
29,Store Street,447,414,592,2327,10782,10641,21423,11262,305,...,1451,247,43,1527,1271,1441,2712,1,6.848610,3128.079865
30,Sundrive Road,334,125,188,495,11993,13239,25232,9789,207,...,2795,562,165,685,2731,2700,5431,7,4.851760,5200.587305
31,Swords,310,219,356,829,24291,24858,49149,23040,342,...,2830,426,93,1388,7232,6796,14028,26,105.245527,466.993718

In [15]:
print(list(df))

['Garda Station', 'Theft', 'Assault & Kidnapping', 'Fraud & Drugs & Weapons', 'Environment & Public Order', 'PopulationTotalMale', 'PopulationTotalFemale', 'PopulationTotal', 'PrincipalStatusAtWork', 'PrincipalStatusLookingForFirstJob', 'PrincipalStatusUnemployed', 'PrincipalStatusStudent', 'PrincipalStatusLookingAfterHome/Family', 'PrincipalStatusRetired', 'PrincipalStatusUnableToWork', 'PrincipalStatusOther', 'SocialClassProfessionalWorkers', 'SocialClassManagerialAndTechnical', 'SocialClassNonManual', 'SocialClassSkilledManual', 'SocialClassSemiSkilled', 'SocialClassUnskilled', 'SocialClassOther', 'AgeEducationCeasedUnder15', 'AgeEducationCeasedAge15', 'AgeEducationCeasedAge16', 'AgeEducationCeasedAge17', 'AgeEducationCeasedAge18', 'AgeEducationCeasedAge19', 'AgeEducationCeasedAge20', 'AgeEducationCeasedAge21+', 'AgeEducationCeasedNotStated', 'EducationNotCeasedStillAtSchool', 'EducationNotCeasedOther', 'HighestLevelEducationNoFormalEducation', 'HighestLevelEducationPrimary', 'HighestLevelEducationLowerSecondary', 'HighestLevelEducationUpperSecondary', 'HighestLevelEducationTechnicalQualification', 'HighestLevelEducationAdvCert/Apprenticeship', 'HighestLevelEducationHigherCertificate', 'HighestLevelEducationOrdinaryBachelorDegree', 'HighestLevelEducationHonoursBachelorDegree', 'HighestLevelEducationPostgraduateDegree', 'HighestLevelEducationDoctorate', 'HighestLevelEducationNotStated', 'GeneralHealthVeryGood', 'GeneralHealthGood', 'GeneralHealthFair', 'GeneralHealthBad', 'GeneralHealthVeryBad', 'GeneralHealthNotStated', 'Total_Under18Male', 'Total_Under18Female', 'Total_Under18', 'Green', 'Area', 'PopulationDensity']

In [16]:
"""df_per5000 = df[['Garda Station', 'PopulationTotal', 'PopulationDensity', 'Green']]
df_per5000['Theft'] =  (df['Theft']/df['PopulationTotal'] * 5000)
df_per5000['Assault&Kidnapping'] =  (df['Assault & Kidnapping']/df['PopulationTotal'] * 5000)
df_per5000['Fraud&Drugs&Weapons'] =  (df['Fraud & Drugs & Weapons']/df['PopulationTotal'] * 5000)
df_per5000['Environment&PublicOrder'] =  (df['Environment & Public Order']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusAtWork'] =  (df['PrincipalStatusAtWork']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusLookingForFirstJob'] =  (df['PrincipalStatusLookingForFirstJob']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusUnemployed'] =  (df['PrincipalStatusUnemployed']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusStudent'] =  (df['PrincipalStatusStudent']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusLookingAfterHome/Family'] =  (df['PrincipalStatusLookingAfterHome/Family']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusUnableToWork'] =  (df['PrincipalStatusUnableToWork']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusOther'] =  (df['PrincipalStatusOther']/df['PopulationTotal'] * 5000)
df_per5000['AgeEducationCeasedNotStated'] =  (df['AgeEducationCeasedNotStated']/df['PopulationTotal'] * 5000)
df_per5000['HighestLevelEducationNotStated'] =  (df['HighestLevelEducationNotStated']/df['PopulationTotal'] * 5000)
df_per5000['GeneralHealthNotStated'] =  (df['GeneralHealthNotStated']/df['PopulationTotal'] * 5000)
df_per5000['NoLowEducation'] =  (df['NoLowEducation']/df['PopulationTotal'] * 5000)
df_per5000['MiddleEducation'] =  (df['MiddleEducation']/df['PopulationTotal'] * 5000)
df_per5000['NoLowEducation'] =  (df['NoLowEducation']/df['PopulationTotal'] * 5000)
df_per5000['HighEducation'] =  (df['HighEducation']/df['PopulationTotal'] * 5000)
df_per5000['LowerSocialClass'] =  (df['LowerSocialClass']/df['PopulationTotal'] * 5000)
df_per5000['HigherSocialClass'] =  (df['HigherSocialClass']/df['PopulationTotal'] * 5000)
df_per5000['EducationCeasedYoung'] =  (df['EducationCeasedYoung']/df['PopulationTotal'] * 5000)
df_per5000['ContinuedEducation'] =  (df['ContinuedEducation']/df['PopulationTotal'] * 5000)
df_per5000['StillinEducation'] =  (df['StillinEducation']/df['PopulationTotal'] * 5000)
df_per5000['EducationCeasedYoung'] =  (df['EducationCeasedYoung']/df['PopulationTotal'] * 5000)
df_per5000['GoodHealth'] =  (df['GoodHealth']/df['PopulationTotal'] * 5000)
df_per5000['PoorHealth'] =  (df['PoorHealth']/df['PopulationTotal'] * 5000)
df_per5000['TotalCrime'] =  (df['TotalCrime']/df['PopulationTotal'] * 5000)"""




# Green per 5000?
# Area per 5000?
# U18 M, F, Total ?

df.head()

,Garda Station,Theft,Assault & Kidnapping,Fraud & Drugs & Weapons,Environment & Public Order,PopulationTotalMale,PopulationTotalFemale,PopulationTotal,PrincipalStatusAtWork,PrincipalStatusLookingForFirstJob,...,GeneralHealthFair,GeneralHealthBad,GeneralHealthVeryBad,GeneralHealthNotStated,Total_Under18Male,Total_Under18Female,Total_Under18,Green,Area,PopulationDensity
0,Balbriggan,40.138092,34.938857,37.226520,97.745612,2442.808419,2557.191581,24042,1911.446635,55.527826,...,340.653856,58.439398,13.725980,106.688295,859.745445,809.416854,1669.162299,9,60.000023,400.699846
1,Ballyfermot,49.312883,31.364444,63.272780,148.663838,2401.646180,2598.353820,27579,1745.349723,61.459806,...,566.010370,98.988361,24.112549,102.795605,621.124769,595.743138,1216.867907,4,8.568579,3218.620030
2,Ballymun,43.598616,50.057670,59.976932,173.471742,2400.922722,2599.077278,21675,1584.775087,62.053057,...,495.963091,98.269896,17.301038,172.779700,690.426759,667.358708,1357.785467,4,7.025158,3085.339783
3,BlackrockCoDublin,37.994871,16.573895,24.391769,55.350554,2345.831509,2654.168491,31978,2161.955094,22.671837,...,294.421165,44.405529,10.163237,79.898680,557.101757,542.404153,1099.505910,3,8.965902,3566.624005
4,Blanchardstown,40.274068,27.682049,29.517323,106.241971,2456.820082,2543.179918,98078,2160.321377,51.336691,...,275.189135,46.085768,9.941067,137.543588,777.697343,739.309529,1517.006872,15,45.287530,2165.673399

In [20]:
df['GreensPerKMSQ'] = df['Green']/df['Area']
df['GreensPerPerson'] = df['Green']/df['PopulationTotal']
df['TotalCrime'] = df[df[1:4]].sum(axis=1)

ValueError: Must pass DataFrame with boolean values only

In [18]:
df.keys()

Index(['Garda Station', 'Theft', 'Assault & Kidnapping',
       'Fraud & Drugs & Weapons', 'Environment & Public Order',
       'PopulationTotalMale', 'PopulationTotalFemale', 'PopulationTotal',
       'PrincipalStatusAtWork', 'PrincipalStatusLookingForFirstJob',
       'PrincipalStatusUnemployed', 'PrincipalStatusStudent',
       'PrincipalStatusLookingAfterHome/Family', 'PrincipalStatusRetired',
       'PrincipalStatusUnableToWork', 'PrincipalStatusOther',
       'SocialClassProfessionalWorkers', 'SocialClassManagerialAndTechnical',
       'SocialClassNonManual', 'SocialClassSkilledManual',
       'SocialClassSemiSkilled', 'SocialClassUnskilled', 'SocialClassOther',
       'AgeEducationCeasedUnder15', 'AgeEducationCeasedAge15',
       'AgeEducationCeasedAge16', 'AgeEducationCeasedAge17',
       'AgeEducationCeasedAge18', 'AgeEducationCeasedAge19',
       'AgeEducationCeasedAge20', 'AgeEducationCeasedAge21+',
       'AgeEducationCeasedNotStated', 'EducationNotCeasedStillAtSchool',
       'EducationNotCeasedOther', 'HighestLevelEducationNoFormalEducation',
       'HighestLevelEducationPrimary', 'HighestLevelEducationLowerSecondary',
       'HighestLevelEducationUpperSecondary',
       'HighestLevelEducationTechnicalQualification',
       'HighestLevelEducationAdvCert/Apprenticeship',
       'HighestLevelEducationHigherCertificate',
       'HighestLevelEducationOrdinaryBachelorDegree',
       'HighestLevelEducationHonoursBachelorDegree',
       'HighestLevelEducationPostgraduateDegree',
       'HighestLevelEducationDoctorate', 'HighestLevelEducationNotStated',
       'GeneralHealthVeryGood', 'GeneralHealthGood', 'GeneralHealthFair',
       'GeneralHealthBad', 'GeneralHealthVeryBad', 'GeneralHealthNotStated',
       'Total_Under18Male', 'Total_Under18Female', 'Total_Under18', 'Green',
       'Area', 'PopulationDensity', 'GreensPerKMSQ', 'GreensPerPerson'],
      dtype='object')

In [19]:
df.to_csv('PerCapita.csv')