<h1>Gathering Crime Data</h1>

- Crime data taken from cso.ie
- Crime data is recorded by Garda division
- As we are looking at smaller populations within Dublin we took the statistics for each garda station within our areas of interest
- We were also limited to areas that we had a green space count for

In [1]:
import pandas as pd

In [2]:
# CRIMEDATADUBGALROS.csv contains a count of all occurrences of crime in our areas of interest
# Dublin is our main area of focus but as we also have green space data for Galway city and Roscommon, these were also
# included incase the data can be used later on in the analysis, therefore crime data was also included for these areas

# The csv was formed on http://www.cso.ie/px/pxeirestat/Statire/SelectVarVal/Define.asp?maintable=CJA07&PLanguage=0
# from our selected stations and downloaded
df_allcrime= pd.read_csv('CRIMEDATADUBGALROS.csv')
df_allcrime.head(40)

,Garda Station,03 Attempts/threats to murder assaults harassments and related offences,04 Dangerous or negligent acts,05 Kidnapping and related offences,06 Robbery extortion and hijacking offences,07 Burglary and related offences,08 Theft and related offences,09 Fraud deception and related offences,10 Controlled drug offences,11 Weapons and Explosives Offences,12 Damage to property and to the environment,13 Public order and other social code offences,15 Offences against government justice procedures and organisation of crime
0,Salthill,66,52,0,3,104,183,13,74,7,163,168,7
1,Galway,340,163,3,31,360,1121,110,180,29,471,1562,223
2,Balbriggan,96,72,0,16,177,510,66,113,22,257,168,45
3,Ballyfermot,82,91,0,22,250,608,22,327,62,368,420,32
4,Ballymun,166,51,3,47,142,514,30,230,46,394,338,20
5,BlackrockCoDublin,58,48,0,13,230,594,96,60,14,181,163,10
6,Blanchardstown,336,207,2,144,646,2225,164,415,110,970,597,517
7,BridewellDublin,117,57,1,75,204,708,49,250,72,434,591,3586
8,Cabinteely,49,34,2,23,207,391,15,59,12,173,126,11
9,Cabra,90,40,0,33,139,470,39,118,15,292,279,27
10,Clontarf,53,46,0,82,333,851,41,72,21,265,196,8
11,Coolock,165,114,0,76,327,932,63,545,94,578,333,40
12,Donnybrook,45,57,1,19,280,703,44,33,12,192,262,3
13,Airport,10,10,8,0,0,135,41,41,14,9,71,2
14,Dun Laoghaire,115,55,0,28,350,977,60,140,24,404,561,250
15,Finglas,244,90,2,95,294,900,70,424,71,653,432,24
16,Fitzgibbon Street,147,54,1,120,267,1030,35,134,75,493,279,17
17,Garristown,5,5,0,1,16,46,3,7,0,18,3,2
18,Howth,35,34,0,17,126,350,35,53,9,114,130,6
19,Irishtown,43,25,0,7,239,697,32,49,7,191,193,2
20,Kevin Street,196,63,1,103,298,983,74,198,75,563,598,25
21,Kilmainham,194,105,1,91,253,940,47,170,73,482,532,25
22,Lucan,78,75,1,30,194,750,46,113,19,259,194,10
23,Lusk,32,49,0,2,79,356,7,40,11,93,70,5
24,Malahide,71,28,1,14,185,508,38,68,8,206,166,1
25,Mountjoy,184,49,1,80,324,893,89,157,46,386,357,65
26,Pearse Street,551,92,1,165,579,4595,271,294,125,585,2851,139
27,Raheny,46,32,0,36,104,343,31,126,22,201,173,6
28,Santry,127,106,1,76,267,994,48,108,19,331,310,18
29,Shankill,65,35,1,21,152,290,20,141,20,226,177,18
30,Skerries,32,19,0,5,43,143,11,19,5,76,54,3
31,Store Street,338,76,1,171,276,4648,214,378,145,619,1654,54
32,Sundrive Road,86,39,0,50,284,343,21,167,28,334,152,9
33,Swords,127,92,1,32,278,969,68,288,18,319,363,147
34,Athleague,3,3,0,0,5,11,1,2,0,2,5,0
35,Ballaghaderreen,30,16,0,0,30,59,13,7,5,21,67,3
36,Boyle,18,1,0,0,25,62,5,10,0,19,31,1
37,Castlerea,33,15,1,0,10,49,5,34,3,21,32,15
38,Keadue,2,1,0,1,5,12,0,0,0,2,1,0
39,Roscommon,36,30,0,0,39,152,10,22,3,52,87,6

In [3]:
# Crime offences were broken into four categories and aggregated
df_crimelist = list(df_allcrime)
df_allcrime["Theft"] = df_allcrime[df_crimelist[4:6]].sum(axis=1)
df_allcrime["Assault & Kidnapping"] = df_allcrime[df_crimelist[1:3]].sum(axis=1)
df_allcrime["Fraud & Drugs & Weapons"] = df_allcrime[df_crimelist[7:9]].sum(axis=1)
df_allcrime["Environment & Public Order"] = df_allcrime[df_crimelist[10:]].sum(axis=1)

df_allcrime.head(40)

,Garda Station,03 Attempts/threats to murder assaults harassments and related offences,04 Dangerous or negligent acts,05 Kidnapping and related offences,06 Robbery extortion and hijacking offences,07 Burglary and related offences,08 Theft and related offences,09 Fraud deception and related offences,10 Controlled drug offences,11 Weapons and Explosives Offences,12 Damage to property and to the environment,13 Public order and other social code offences,15 Offences against government justice procedures and organisation of crime,Theft,Assault & Kidnapping,Fraud & Drugs & Weapons,Environment & Public Order
0,Salthill,66,52,0,3,104,183,13,74,7,163,168,7,107,118,87,338
1,Galway,340,163,3,31,360,1121,110,180,29,471,1562,223,391,503,290,2256
2,Balbriggan,96,72,0,16,177,510,66,113,22,257,168,45,193,168,179,470
3,Ballyfermot,82,91,0,22,250,608,22,327,62,368,420,32,272,173,349,820
4,Ballymun,166,51,3,47,142,514,30,230,46,394,338,20,189,217,260,752
5,BlackrockCoDublin,58,48,0,13,230,594,96,60,14,181,163,10,243,106,156,354
6,Blanchardstown,336,207,2,144,646,2225,164,415,110,970,597,517,790,543,579,2084
7,BridewellDublin,117,57,1,75,204,708,49,250,72,434,591,3586,279,174,299,4611
8,Cabinteely,49,34,2,23,207,391,15,59,12,173,126,11,230,83,74,310
9,Cabra,90,40,0,33,139,470,39,118,15,292,279,27,172,130,157,598
10,Clontarf,53,46,0,82,333,851,41,72,21,265,196,8,415,99,113,469
11,Coolock,165,114,0,76,327,932,63,545,94,578,333,40,403,279,608,951
12,Donnybrook,45,57,1,19,280,703,44,33,12,192,262,3,299,102,77,457
13,Airport,10,10,8,0,0,135,41,41,14,9,71,2,0,20,82,82
14,Dun Laoghaire,115,55,0,28,350,977,60,140,24,404,561,250,378,170,200,1215
15,Finglas,244,90,2,95,294,900,70,424,71,653,432,24,389,334,494,1109
16,Fitzgibbon Street,147,54,1,120,267,1030,35,134,75,493,279,17,387,201,169,789
17,Garristown,5,5,0,1,16,46,3,7,0,18,3,2,17,10,10,23
18,Howth,35,34,0,17,126,350,35,53,9,114,130,6,143,69,88,250
19,Irishtown,43,25,0,7,239,697,32,49,7,191,193,2,246,68,81,386
20,Kevin Street,196,63,1,103,298,983,74,198,75,563,598,25,401,259,272,1186
21,Kilmainham,194,105,1,91,253,940,47,170,73,482,532,25,344,299,217,1039
22,Lucan,78,75,1,30,194,750,46,113,19,259,194,10,224,153,159,463
23,Lusk,32,49,0,2,79,356,7,40,11,93,70,5,81,81,47,168
24,Malahide,71,28,1,14,185,508,38,68,8,206,166,1,199,99,106,373
25,Mountjoy,184,49,1,80,324,893,89,157,46,386,357,65,404,233,246,808
26,Pearse Street,551,92,1,165,579,4595,271,294,125,585,2851,139,744,643,565,3575
27,Raheny,46,32,0,36,104,343,31,126,22,201,173,6,140,78,157,380
28,Santry,127,106,1,76,267,994,48,108,19,331,310,18,343,233,156,659
29,Shankill,65,35,1,21,152,290,20,141,20,226,177,18,173,100,161,421
30,Skerries,32,19,0,5,43,143,11,19,5,76,54,3,48,51,30,133
31,Store Street,338,76,1,171,276,4648,214,378,145,619,1654,54,447,414,592,2327
32,Sundrive Road,86,39,0,50,284,343,21,167,28,334,152,9,334,125,188,495
33,Swords,127,92,1,32,278,969,68,288,18,319,363,147,310,219,356,829
34,Athleague,3,3,0,0,5,11,1,2,0,2,5,0,5,6,3,7
35,Ballaghaderreen,30,16,0,0,30,59,13,7,5,21,67,3,30,46,20,91
36,Boyle,18,1,0,0,25,62,5,10,0,19,31,1,25,19,15,51
37,Castlerea,33,15,1,0,10,49,5,34,3,21,32,15,10,48,39,68
38,Keadue,2,1,0,1,5,12,0,0,0,2,1,0,6,3,0,3
39,Roscommon,36,30,0,0,39,152,10,22,3,52,87,6,39,66,32,145

In [4]:
# Drop individual crime rows (these are all now containined in our aggregated columns so are no longer needed)
df_allcrime = df_allcrime.drop(['03 Attempts/threats to murder assaults harassments and related offences', 
                                '04 Dangerous or negligent acts',
                                '05 Kidnapping and related offences',
                                '06 Robbery extortion and hijacking offences',
                                '07 Burglary and related offences',
                                '08 Theft and related offences',
                                '09 Fraud deception and related offences',
                                '10 Controlled drug offences',
                                '11 Weapons and Explosives Offences',
                                '12 Damage to property and to the environment',
                                '13 Public order and other social code offences',
                                '15 Offences against government justice procedures and organisation of crime'], axis=1)
df_allcrime['TotalCrime'] = df_allcrime['Theft'] + df_allcrime['Assault & Kidnapping'] + df_allcrime['Fraud & Drugs & Weapons'] + df_allcrime['Environment & Public Order']

df_allcrime.head(40)

,Garda Station,Theft,Assault & Kidnapping,Fraud & Drugs & Weapons,Environment & Public Order,TotalCrime
0,Salthill,107,118,87,338,650
1,Galway,391,503,290,2256,3440
2,Balbriggan,193,168,179,470,1010
3,Ballyfermot,272,173,349,820,1614
4,Ballymun,189,217,260,752,1418
5,BlackrockCoDublin,243,106,156,354,859
6,Blanchardstown,790,543,579,2084,3996
7,BridewellDublin,279,174,299,4611,5363
8,Cabinteely,230,83,74,310,697
9,Cabra,172,130,157,598,1057
10,Clontarf,415,99,113,469,1096
11,Coolock,403,279,608,951,2241
12,Donnybrook,299,102,77,457,935
13,Airport,0,20,82,82,184
14,Dun Laoghaire,378,170,200,1215,1963
15,Finglas,389,334,494,1109,2326
16,Fitzgibbon Street,387,201,169,789,1546
17,Garristown,17,10,10,23,60
18,Howth,143,69,88,250,550
19,Irishtown,246,68,81,386,781
20,Kevin Street,401,259,272,1186,2118
21,Kilmainham,344,299,217,1039,1899
22,Lucan,224,153,159,463,999
23,Lusk,81,81,47,168,377
24,Malahide,199,99,106,373,777
25,Mountjoy,404,233,246,808,1691
26,Pearse Street,744,643,565,3575,5527
27,Raheny,140,78,157,380,755
28,Santry,343,233,156,659,1391
29,Shankill,173,100,161,421,855
30,Skerries,48,51,30,133,262
31,Store Street,447,414,592,2327,3780
32,Sundrive Road,334,125,188,495,1142
33,Swords,310,219,356,829,1714
34,Athleague,5,6,3,7,21
35,Ballaghaderreen,30,46,20,91,187
36,Boyle,25,19,15,51,110
37,Castlerea,10,48,39,68,165
38,Keadue,6,3,0,3,12
39,Roscommon,39,66,32,145,282

In [5]:
# Save dataframe of crime occurences to a csv file
df_allcrime.head(34)
df_allcrime.to_csv('CrimeAll.csv')

In [6]:
# save dataframe contining crime occurences for just the Dublin Subdivisions to a csv
crime_dublin = df_allcrime.loc[2:33]
crime_dublin.to_csv('CrimeDublin.csv')

In [7]:

df_allcrime.describe().T

,count,mean,std,min,25%,50%,75%,max
Theft,40.0,246.250,186.109941,0.0,100.50,236.5,380.25,790.0
Assault & Kidnapping,40.0,168.550,149.003347,3.0,68.75,121.5,222.50,643.0
Fraud & Drugs & Weapons,40.0,192.825,172.322876,0.0,76.25,157.0,263.00,608.0
Environment & Public Order,40.0,788.625,964.871658,3.0,229.50,466.0,859.50,4611.0
TotalCrime,40.0,1396.250,1357.937855,12.0,506.75,1004.5,1760.25,5527.0