In [7]:
import pandas as pd

df = pd.read_csv('CombinedFinalDublin.csv')
df= df.drop('Unnamed: 0', 1)
df.head(32)

,Garda Station,Theft,Assault & Kidnapping,Fraud & Drugs & Weapons,Environment & Public Order,PopulationTotalMale,PopulationTotalFemale,PopulationTotal,PrincipalStatusAtWork,PrincipalStatusLookingForFirstJob,...,HighEducation,LowerSocialClass,HigherSocialClass,EducationCeasedYoung,ContinuedEducation,StillinEducation,GoodHealth,PoorHealth,TotalCrime,PopulationDensity
0,Balbriggan,193,168,179,470,11746,12296,24042,9191,267,...,2857,3520,11808,3946,7305,1582,21544,281,540,400.699846
1,Ballyfermot,272,173,349,820,13247,14332,27579,9627,339,...,2445,5774,10421,9478,7067,1247,23211,546,794,3218.620030
2,Ballymun,189,217,260,752,10408,11267,21675,6870,269,...,1728,3939,7983,5583,5804,1405,18275,426,666,3085.339783
3,BlackrockCoDublin,243,106,156,354,15003,16975,31978,13827,145,...,11511,1272,24996,2623,15370,1153,29235,284,505,3566.624005
4,Blanchardstown,790,543,579,2084,48192,49886,98078,42376,1007,...,18095,11573,55093,13173,34990,7495,88883,904,1912,2165.673399
5,BridewellDublin,279,174,299,4611,11883,11111,22994,10800,340,...,5417,4010,10132,4071,9569,1983,19394,438,752,7651.860597
6,Cabinteely,230,83,74,310,15800,16954,32754,13227,153,...,8284,2226,23632,4290,13650,1195,29667,303,387,1779.005778
7,Cabra,172,130,157,598,10342,11509,21851,9363,184,...,4010,3269,11509,5234,7904,1096,18719,371,459,1923.509972
8,Clontarf,415,99,113,469,17749,19494,37243,16745,244,...,9570,3112,25690,6116,15666,1501,33112,419,627,2059.529726
9,Coolock,403,279,608,951,25244,26969,52213,20131,418,...,4939,8860,23107,14275,15355,2354,45235,795,1290,2953.743672
10,Donnybrook,299,102,77,457,13507,15191,28698,13484,129,...,10854,1306,19173,2153,14939,1304,25102,342,478,3491.432368
11,Airport,0,20,82,82,260,147,407,263,2,...,144,17,229,31,270,23,321,4,102,65.255415
12,Dun Laoghaire,378,170,200,1215,17676,19938,37614,15146,176,...,10686,3082,26192,5492,16827,1295,33222,502,748,3346.585953
13,Finglas,389,334,494,1109,19732,21313,41045,15742,394,...,4033,7454,17051,10247,12892,2412,34874,711,1217,1074.760818
14,Fitzgibbon Street,387,201,169,789,9828,9500,19328,8250,430,...,3203,3465,6608,3188,7707,1967,15622,398,757,10309.834669
15,Garristown,17,10,10,23,1893,1793,3686,1440,20,...,444,465,2043,675,1259,137,3306,32,37,44.298767
16,Howth,143,69,88,250,10045,10889,20934,8503,97,...,5021,1630,14484,3468,8737,677,18826,235,300,1444.968583
17,Irishtown,246,68,81,386,11222,12447,23669,13231,114,...,9434,1784,16763,2497,13331,1276,21237,214,395,1770.284709
18,Kevin Street,401,259,272,1186,14740,14332,29072,13293,410,...,6634,4706,12363,4817,11662,2484,24571,476,932,10478.366461
19,Kilmainham,344,299,217,1039,11724,12183,23907,11192,228,...,5811,3653,11439,4596,10292,1758,19757,524,860,4913.336912
20,Lucan,224,153,159,463,16999,17770,34769,15299,228,...,7029,3485,22060,4391,12507,1955,31933,287,536,1286.237047
21,Lusk,81,81,47,168,8969,9311,18280,7739,132,...,2670,2445,10134,3106,6158,730,16572,196,209,335.018127
22,Malahide,199,99,106,373,15674,16218,31892,14378,171,...,8023,1992,23374,3953,13501,1179,29391,223,404,1433.200106
23,Mountjoy,404,233,246,808,11890,11029,22919,9887,257,...,4990,3099,10989,3614,9949,2018,18813,362,883,5659.055363
24,Pearse Street,744,643,565,3575,9682,9222,18904,10079,200,...,5275,1758,8787,2319,9383,1583,15365,179,1952,5940.879322
25,Raheny,140,78,157,380,11890,13097,24987,9641,147,...,4429,2965,14968,5730,9083,753,21669,438,375,1829.891495
26,Santry,343,233,156,659,16713,18973,35686,14141,237,...,6453,4192,19001,7575,13204,1664,30488,668,732,2358.014011
27,Shankill,173,100,161,421,10929,11765,22694,9171,174,...,4390,2541,13908,3781,8645,920,20301,256,434,1095.320316
28,Skerries,48,51,30,133,5567,5844,11411,4358,74,...,2243,1037,7540,1735,4258,371,10360,108,129,372.843897
29,Store Street,447,414,592,2327,10782,10641,21423,11262,305,...,4983,3148,8993,2414,9519,2679,18155,247,1453,3128.079865
30,Sundrive Road,334,125,188,495,11993,13239,25232,9789,207,...,3671,4783,10851,7683,7925,1172,21025,562,647,5200.587305
31,Swords,310,219,356,829,24291,24858,49149,23040,342,...,8029,6548,28373,7663,17744,2695,44412,426,885,466.993718

In [3]:
print(list(df))

['Garda Station', 'Theft', 'Assault & Kidnapping', 'Fraud & Drugs & Weapons', 'Environment & Public Order', 'PopulationTotalMale', 'PopulationTotalFemale', 'PopulationTotal', 'PrincipalStatusAtWork', 'PrincipalStatusLookingForFirstJob', 'PrincipalStatusUnemployed', 'PrincipalStatusStudent', 'PrincipalStatusLookingAfterHome/Family', 'PrincipalStatusRetired', 'PrincipalStatusUnableToWork', 'PrincipalStatusOther', 'AgeEducationCeasedNotStated', 'HighestLevelEducationNotStated', 'GeneralHealthNotStated', 'Total_Under18Male', 'Total_Under18Female', 'Total_Under18', 'Green', 'Area', 'NoLowEducation', 'MiddleEducation', 'HighEducation', 'LowerSocialClass', 'HigherSocialClass', 'EducationCeasedYoung', 'ContinuedEducation', 'StillinEducation', 'GoodHealth', 'PoorHealth', 'TotalCrime', 'PopulationDensity']

In [26]:
df_per5000 = df[['Garda Station', 'PopulationTotal', 'PopulationDensity', 'Green']]
df_per5000['Theft'] =  (df['Theft']/df['PopulationTotal'] * 5000)
df_per5000['Assault&Kidnapping'] =  (df['Assault & Kidnapping']/df['PopulationTotal'] * 5000)
df_per5000['Fraud&Drugs&Weapons'] =  (df['Fraud & Drugs & Weapons']/df['PopulationTotal'] * 5000)
df_per5000['Environment&PublicOrder'] =  (df['Environment & Public Order']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusAtWork'] =  (df['PrincipalStatusAtWork']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusLookingForFirstJob'] =  (df['PrincipalStatusLookingForFirstJob']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusUnemployed'] =  (df['PrincipalStatusUnemployed']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusStudent'] =  (df['PrincipalStatusStudent']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusLookingAfterHome/Family'] =  (df['PrincipalStatusLookingAfterHome/Family']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusUnableToWork'] =  (df['PrincipalStatusUnableToWork']/df['PopulationTotal'] * 5000)
df_per5000['PrincipalStatusOther'] =  (df['PrincipalStatusOther']/df['PopulationTotal'] * 5000)
df_per5000['AgeEducationCeasedNotStated'] =  (df['AgeEducationCeasedNotStated']/df['PopulationTotal'] * 5000)
df_per5000['HighestLevelEducationNotStated'] =  (df['HighestLevelEducationNotStated']/df['PopulationTotal'] * 5000)
df_per5000['GeneralHealthNotStated'] =  (df['GeneralHealthNotStated']/df['PopulationTotal'] * 5000)
df_per5000['NoLowEducation'] =  (df['NoLowEducation']/df['PopulationTotal'] * 5000)
df_per5000['MiddleEducation'] =  (df['MiddleEducation']/df['PopulationTotal'] * 5000)
df_per5000['NoLowEducation'] =  (df['NoLowEducation']/df['PopulationTotal'] * 5000)
df_per5000['HighEducation'] =  (df['HighEducation']/df['PopulationTotal'] * 5000)
df_per5000['LowerSocialClass'] =  (df['LowerSocialClass']/df['PopulationTotal'] * 5000)
df_per5000['HigherSocialClass'] =  (df['HigherSocialClass']/df['PopulationTotal'] * 5000)
df_per5000['EducationCeasedYoung'] =  (df['EducationCeasedYoung']/df['PopulationTotal'] * 5000)
df_per5000['ContinuedEducation'] =  (df['ContinuedEducation']/df['PopulationTotal'] * 5000)
df_per5000['StillinEducation'] =  (df['StillinEducation']/df['PopulationTotal'] * 5000)
df_per5000['EducationCeasedYoung'] =  (df['EducationCeasedYoung']/df['PopulationTotal'] * 5000)
df_per5000['GoodHealth'] =  (df['GoodHealth']/df['PopulationTotal'] * 5000)
df_per5000['PoorHealth'] =  (df['PoorHealth']/df['PopulationTotal'] * 5000)
df_per5000['TotalCrime'] =  (df['TotalCrime']/df['PopulationTotal'] * 5000)

# Green per 5000?
# Area per 5000?
# U18 M, F, Total ?


df_per5000.head()

/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/JoanMcCarthy/anaconda/envs/comp47350/lib/python3.5/site-packages/ipykernel/__main__.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Garda Station,PopulationTotal,PopulationDensity,Green,Theft,Assault&Kidnapping,Fraud&Drugs&Weapons,Environment&PublicOrder,PrincipalStatusAtWork,PrincipalStatusLookingForFirstJob,...,MiddleEducation,HighEducation,LowerSocialClass,HigherSocialClass,EducationCeasedYoung,ContinuedEducation,StillinEducation,GoodHealth,PoorHealth,TotalCrime
0,Balbriggan,24042,400.699846,9,40.138092,34.938857,37.226520,97.745612,1911.446635,55.527826,...,520.547375,594.168538,732.052242,2455.702521,820.647201,1519.216371,329.007570,4480.492472,58.439398,112.303469
1,Ballyfermot,27579,3218.620030,4,49.312883,31.364444,63.272780,148.663838,1745.349723,61.459806,...,409.188150,443.272055,1046.810979,1889.299830,1718.336415,1281.228471,226.077813,4208.093114,98.988361,143.950107
2,Ballymun,21675,3085.339783,4,43.598616,50.057670,59.976932,173.471742,1584.775087,62.053057,...,367.243368,398.615917,908.650519,1841.522491,1287.889273,1338.869666,324.106113,4215.686275,98.269896,153.633218
3,BlackrockCoDublin,31978,3566.624005,3,37.994871,16.573895,24.391769,55.350554,2161.955094,22.671837,...,253.611858,1799.831134,198.886735,3908.311964,410.125711,2403.214710,180.280193,4571.111389,44.405529,78.960535
4,Blanchardstown,98078,2165.673399,15,40.274068,27.682049,29.517323,106.241971,2160.321377,51.336691,...,427.414915,922.480067,589.989600,2808.631905,671.557332,1783.784335,382.093844,4531.240441,46.085768,97.473440

In [27]:
df_per5000.to_csv('per5000.csv')